### ISSUE TITLE
SyntaxError: invalid syntax when running baku --init

### ISSUE THREAD

**Issue by infobeisel** [vladris/baku#10]
first of all thank you for developing this!

on my ubuntu machine with python 3.8.10 and baku installed by pip.

pip show baku

Name: Baku
Version: 1.0.1
Summary: Simple, Markdown-based blogging engine
Home-page: http://github.com/vladris/baku/
Author: Vlad Riscutia
Author-email: vladris@outlook.com
License: MIT
Location: /home/beisel/.local/lib/python3.8/site-packages
Requires: misaka, Pygments, pyquery
Required-by:

when i try to init a blog:

baku --init

Traceback (most recent call last):
  File "/home/beisel/.local/bin/baku", line 5, in <module>
    from baku.cmdline import main
  File "/home/beisel/.local/lib/python3.8/site-packages/baku/cmdline.py", line 4, in <module>
    from baku import build, document, environment, upgrade, utils
  File "/home/beisel/.local/lib/python3.8/site-packages/baku/build.py", line 4, in <module>
    from baku import consts, index, environment, markdown, post, rss, templating, utils
  File "/home/beisel/.local/lib/python3.8/site-packages/baku/index.py", line 3, in <module>
    from baku import consts, post, templating, utils
  File "/home/beisel/.local/lib/python3.8/site-packages/baku/post.py", line 4, in <module>
    from baku import templating, utils
  File "/home/beisel/.local/lib/python3.8/site-packages/baku/templating.py", line 90
    match node.type:
          ^
SyntaxError: invalid syntax

**Comment by infobeisel** [comment]
nvm, i realized i have only python 3.8 installed, but i seem to need 3.10 to support this syntax, right?
